//const admin = require('./admin')

module.exports = app => {
    app.post('/signup', app.api.user.insert)
    app.post('/signin', app.api.auth.signin)
    app.post('/validateToken', app.api.auth.validateToken)

    app.route('/users')
        .all(app.config.passport.authenticate())
        .get(app.api.user.get)
        .post(app.api.user.insert)

    app.route('/users/:id')
        .all(app.config.passport.authenticate())
        // .get(admin(app.api.user.getById))
        .get(app.api.user.getById)
        // .put(admin(app.api.user.save))
        .put(app.api.user.update)
        // .delete(admin(app.api.user.remove))
        .delete(app.api.user.remove)

    app.route('/exams')
        .all(app.config.passport.authenticate())
        .get(app.api.exam.get)
        .post(app.api.exam.insert)

    app.route('/exams/:id')
        .all(app.config.passport.authenticate())
        // .get(admin(app.api.exam.getById))
        .get(app.api.exam.getById)
        // .put(admin(app.api.exam.save))
        .put(app.api.exam.update)
        // .delete(admin(app.api.exam.remove))
        .delete(app.api.exam.remove)

    app.route('/diseases')
        .all(app.config.passport.authenticate())
        .get(app.api.disease.get)
        .post(app.api.disease.insert)

    app.route('/diseases/:id')
        .all(app.config.passport.authenticate())
        // .get(admin(app.api.disease.getById))
        .get(app.api.disease.getById)
        // .put(admin(app.api.disease.save))
        .put(app.api.disease.update)
        // .delete(admin(app.api.disease.remove))
        .delete(app.api.disease.remove)
    
    app.route('/consultings')
        .all(app.config.passport.authenticate())
        .get(app.api.consulting.get)
        .post(app.api.consulting.insert)

    app.route('/consultings/:id')
        .all(app.config.passport.authenticate())
        // .get(admin(app.api.consulting.getById))
        .get(app.api.consulting.getById)
        // .put(admin(app.api.consulting.save))
        .put(app.api.consulting.update)
        // .delete(admin(app.api.consulting.remove))
        .delete(app.api.consulting.remove)
}